Attaching to 1619597041530066606fbd4eb6822e5c6fb6ae8cv60775cedfe369382b2c922af_fwd-server-a_1, 1619597041530066606fbd4eb6822e5c6fb6ae8cv60775cedfe369382b2c922af_game-server_1, 1619597041530066606fbd4eb6822e5c6fb6ae8cv60775cedfe369382b2c922af_fwd-server-b_1, 1619597041530066606fbd4eb6822e5c6fb6ae8cv60775cedfe369382b2c922af_agent-b_1, 1619597041530066606fbd4eb6822e5c6fb6ae8cv60775cedfe369382b2c922af_agent-a_1
[36;1magent-b_1       |[0m Task exception was never retrieved
[36;1magent-b_1       |[0m future: <Task finished name='Task-5' coro=<GameState._handle_messages() done, defined at /app/game_state.py:41> exception=AttributeError("'NoneType' object has no attribute 'get'")>
[36;1magent-b_1       |[0m Traceback (most recent call last):
[36;1magent-b_1       |[0m   File "/app/game_state.py", line 46, in _handle_messages
[36;1magent-b_1       |[0m     await self._on_data(data)
[36;1magent-b_1       |[0m   File "/app/game_state.py", line 62, in _on_data
[36;1magent-b_1       |[0m     await self._tick_callback(0, self._state)
[36;1magent-b_1       |[0m   File "/app/agent.py", line 168, in _on_game_tick
[36;1magent-b_1       |[0m     self.update_players()
[36;1magent-b_1       |[0m   File "/app/agent.py", line 127, in update_players
[36;1magent-b_1       |[0m     myId = self._client._state.get("connection").get("agent_number")
[36;1magent-b_1       |[0m AttributeError: 'NoneType' object has no attribute 'get'
[33m1619597041530066606fbd4eb6822e5c6fb6ae8cv60775cedfe369382b2c922af_agent-b_1 exited with code 0
[0mAborting on container exit...
