Attaching to 1619856585451101606fbd4eb6822e5c6fb6ae8cv60712d03b6822e5c6fbd0f02-34_fwd-server-a_1, 1619856585451101606fbd4eb6822e5c6fb6ae8cv60712d03b6822e5c6fbd0f02-34_fwd-server-b_1, 1619856585451101606fbd4eb6822e5c6fb6ae8cv60712d03b6822e5c6fbd0f02-34_game-server_1, 1619856585451101606fbd4eb6822e5c6fb6ae8cv60712d03b6822e5c6fbd0f02-34_agent-b_1, 1619856585451101606fbd4eb6822e5c6fb6ae8cv60712d03b6822e5c6fbd0f02-34_agent-a_1
[36;1magent-b_1       |[0m ws://game-server:3000/?role=agent&agentId=24601&name=agent-b
[36;1magent-b_1       |[0m ERROR:asyncio:Task exception was never retrieved
[36;1magent-b_1       |[0m future: <Task finished name='Task-5' coro=<GameState._handle_messages() done, defined at /app/src/game_state.py:39> exception=AttributeError("'Agent' object has no attribute 'my_agent_number'")>
[36;1magent-b_1       |[0m Traceback (most recent call last):
[36;1magent-b_1       |[0m   File "/app/src/game_state.py", line 44, in _handle_messages
[36;1magent-b_1       |[0m     await self._on_data(data)
[36;1magent-b_1       |[0m   File "/app/src/game_state.py", line 60, in _on_data
[36;1magent-b_1       |[0m     await self._on_game_tick(payload)
[36;1magent-b_1       |[0m   File "/app/src/game_state.py", line 90, in _on_game_tick
[36;1magent-b_1       |[0m     await self._tick_callback(tick_number, self._state)
[36;1magent-b_1       |[0m   File "/app/src/agent.py", line 224, in _on_game_tick
[36;1magent-b_1       |[0m     self._on_each_tick(game_state)
[36;1magent-b_1       |[0m   File "/app/src/agent.py", line 99, in _on_each_tick
[36;1magent-b_1       |[0m     self.my_loc = game_state['agent_state'][self.my_agent_number]['coordinates']
[36;1magent-b_1       |[0m AttributeError: 'Agent' object has no attribute 'my_agent_number'
[33m1619856585451101606fbd4eb6822e5c6fb6ae8cv60712d03b6822e5c6fbd0f02-34_agent-b_1 exited with code 0
[0mAborting on container exit...
